a=0b101
b=10
c=0o123
d=0x12c

float_1=5.5
float_2=2.5e3
x=5+3j

print(a,b,c,d)
print(float_1,float_2)
print(x,x.real,x.imag)
#-------

a=True
b=False
c=a+b
print(type(c))
print(c)

#------------

a = True
b = False

print("a:", a, "b:", b)
print("a + b =", a + b)
print("a * b =", a * b)
print("a == b:", a == b)
print("a or b:", a or b)
print("a and b:", a and b)

#------------
z1 = 3 + 4j
z2 = 1 - 2j
z3 = z1 * z2

print("z1:", z1,
print("z2:", z2)
print("z1 * z2:", z3)


