string1 = "Hello, World!"
print(string1)


string2 = 'Python is fun'
print(string2)


first = "Hello"
second = "World"
result = first + " " + second
print(result)



a = "Python"
b = "Rocks"
print(a + " " + b + "!")



word = "Programming"
print(word[0])    # First character
print(word[-1])   # Last character




text = "Hello, World!"
print(text[0:5])    # 'Hello'
print(text[7:])     # 'World!'




~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
~                                                                                                                                             
"str.py" 
